name = input()
price = int(input())
weight = int(input())
cash = int(input())
print("Чек")
print(name , weight,"кг", price,"руб")
print("Итого:", weight * price,"руб")
print("Внесено:", cash,"руб")
print("Сдача:", cash - weight * price,"руб")